### ISSUE TITLE
Slashless?

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby-docker#1]
http://stackoverflow.com/questions/645853/add-slash-to-the-end-of-every-url-need-rewrite-rule-for-nginx

**Comment by deniaz** [comment]
This should now be configurable thanks to this MR: https://github.com/gatsbyjs/gatsby-docker/pull/7#issuecomment-329773891

**Comment by mfeltscher** [comment]
Yes, indeed, this is now configurable using the `$TRAILING_SLASH ` environment variable.

**Comment by cusspvz** [comment]
This could be closed since it has already been deployed.
