### ISSUE TITLE
Is this using the latest version of gatsby?

### ISSUE THREAD

**Issue by loganpowell** [gatsbyjs/gatsby-docker#10]
I'm on Windows and really like the idea of using docker to get around all the different OS idiosyncrasies. Is this up to date?

**Comment by KyleAMathews** [comment]
This is just for building & hosting Gatsby websites — if you want to develop Gatsby in Docker, you'd need another image. Probably just something that's setup for Node.js development. Not really sure what that'd be but if you find a great setup, I'm sure others would love to hear back about it!

**Comment by loganpowell** [comment]
I found this:

https://hub.docker.com/r/asifrc/gatsbyjs-dev/~/dockerfile/

Look promising?

**Comment by KyleAMathews** [comment]
Looks old as they're on node 6 and expose port 3000 which we stopped working but should still work!

**Comment by loganpowell** [comment]
Does this look better:

https://hub.docker.com/r/optimized/docker-gatsbyjs/

Sorry, I'm new
