### ISSUE TITLE
Port-mapping doesn't work

### ISSUE THREAD

**Issue by designbyadrian** [gatsbyjs/gatsby-docker#13]
Running this command:

`docker run -d --rm myproject/website .` exposes no site on localhost...

but

`docker run -d -p 80:80 --rm myproject/website .` does.

Am I just being clueless about how Docker works?

**Comment by rc1** [comment]
That's how docker works. Docker won't publish a container's port(s) to the host unless you explicitly say so with the `-p` parameter.
