### ISSUE TITLE
Pull access denied for gatsby

### ISSUE THREAD

**Issue by mrhut10** [gatsbyjs/gatsby-docker#16]
Tried to pull image and I'm getting this error,

will creating a login at docker hub fix this or do i need further permissions

thank you in advanced

''Unable to find image 'gatsby:latest' locally
ddocker: Error response from daemon: pull access denied for gatsby, repository does not exist or may require 'docker login'.''

**Comment by mrhut10** [comment]
For the moment i will just switch to a node:slim docker image, and install 
git & gatsby-cli i think it will get around the problem,, and i can come back and use this project once I hear from someone in this regard.

**Comment by cusspvz** [comment]
Current gatsby docker image only serves builds that were generated previously, using an NGINX server.

> Unable to find image 'gatsby:latest' locally

Are you using `gatsby:latest` instead of `gatsby/gatsby:latest` ?

**Comment by mrhut10** [comment]
gatsbyjs/gatsby:onbuild
??

**Comment by mrhut10** [comment]
and i can't pretend to have any experience or know how with what the "nginx" :(

**Comment by aslafy-z** [comment]
I guess you are looking for something like this: https://github.com/aripalo/gatsby-docker/

**Comment by cusspvz** [comment]
closing issue since it's already being tracked at #11
