### ISSUE TITLE
Image at docker store is not working

### ISSUE THREAD

**Issue by krahser** [gatsbyjs/gatsby-docker#4]
Hi!

Nice project.

I recently run the image and this is the error.

`docker run --rm   gatsbyjs/gatsby
/sbin/nginx-boot: line 83: syntax error near unexpected token `then'
/sbin/nginx-boot: line 83: `if [ "" != "$DEBUG" ]; then'
`

Opening the file with:
`docker run --rm   -it gatsbyjs/gatsby vi /sbin/nginx-boot`

I saw that there are .. in between the if  and [. 
Using cat I can't see that.

After modify that the error is:

`bash-4.3# nginx-boot
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
`

If I create the /run/nginx directory, nginx works, but not yet gatsby.

**Comment by KyleAMathews** [comment]
@cusspvz any idea what's happening?

**Comment by cusspvz** [comment]
@KyleAMathews Fixed. Thanks for noticing it @krahser.

**Comment by cusspvz** [comment]
@krahser You can also use the `onbuild` tag which already has the command for adding the `public/` folder.

**Comment by KyleAMathews** [comment]
Thanks!
