### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by KevinBurton** [gatsbyjs/gatsby-docker#44]
Looking at the README I see that I can  run the app on an HTTP port. How is it suggested that I use HTTPS instead?

**Comment by yairau** [comment]
I think you can use [ngrok](https://github.com/gtriggiano/ngrok-tunnel) for that. I didn't try it yet so don't know for sure but it should work.

**Comment by gardner** [comment]
@KevinBurton you will generally want to use something like caddy or traefik to do HTTPS termination for you and then route to the gatsby container from there. HTTPS is out of scope for a container like this.

**Comment by jamo** [comment]
@KevinBurton what's the use case for having the gatsby-docker setup support HTTPS? 


Indeed, ideally, you will have nginx/(apache) or some similar thing that terminates the HTTPS traffic on the edge, or in case of a single VPS you'd have it installed on the VPS, and then that would route requests to your gatsby-container over HTTP.

**Comment by gardner** [comment]
As a non-contributor community member: please close this ticket. Cheers!
