### ISSUE TITLE
Curious why the Dockerfile uses `FROM alpine:edge` insted of `FROM nginx:alpine`

### ISSUE THREAD

**Issue by rturk** [gatsbyjs/gatsby-docker#6]
I'm curious why the Dockerfile is not starting with `FROM nginx:alpine`

https://hub.docker.com/_/nginx/

**Comment by cusspvz** [comment]
@rturk I made this Dockerfile before the nginx community created their alpine version, inspite my commit was made nearby the nov of 2016, this was based on my [nginx alpine implementation](https://github.com/cusspvz/nginx.docker/commits/master).

Can i ask why are you asking? Are you running some issues with it? Thanks!

**Comment by cusspvz** [comment]
Closing since we didn't got any response from the OP
